### ISSUE TITLE
Upgrade leveldown to at least 3.0.2 to support use on iOS and Android

### ISSUE THREAD

**Issue by mistakia** [orbitdb/orbit-db-cache#6]
After 3.0.2 - Level/leveldown#447, leveldown has support for compilation on iOS and Android. It would be great if we could update it to at least 3.0.2.

This would allow me to use orbit-db on mobile via nodejs-mobile. Glad to help out if needed.

**Comment by guysv** [comment]
+1, We cannot build this package on npm 10

**Comment by haadcode** [comment]
Published to npm as [v0.2.4](http://npmjs.com/package/orbit-db-cache).
